export const BASE_VOUCHES = [
  {
    service: "V-Bucks",
    text: "just purchased 13,500 vbucks 😂 gift cards came super fast like 7 mins max, ty bro",
  },
  {
    service: "Fortnite Account",
    text: "big vouch got the fortnite account with full email access and everything, great price fr 🔥 VeeX trusted",
  },
  {
    service: "V-Bucks",
    text: "bought some v-bucks for my lil bro lol thanks again man!!! 🫶🫶 legit seller",
  },
  {
    service: "Valorant Points",
    text: "vouch++ received the valorant points instantly thank youu so much, VeeX goated",
  },
  {
    service: "Valorant Account",
    text: "vouching hard for the valorant account, full access with email and logins, ty!! also bought vp and codes worked perfect +rep VeeX",
  },
  {
    service: "Robux & V-Bucks",
    text: "tested with 5000 robux first got it quick then went for 27k vbucks, codes all worked vouching this shop 💯 trusted af",
  },
  {
    service: "R6 Credits",
    text: "just copped 15k r6 credits legit and delivered in minutes, VeeX best prices",
  },
  {
    service: "Riot Buddy",
    text: "vouch for the riot buddy service even hooked me up with a discount ty gng 😎 safe deal",
  },
  {
    service: "R6 Account",
    text: "best place for r6 stuff hands down, got account + credits smooth, +vouch veex",
  },
  {
    service: "Headless & Korblox",
    text: "bought headless and korblox combo acc, super fast delivery and 100% legit 😍❤️ VeeX legit",
  },
  {
    service: "General",
    text: "trustworthy af, excellent transaction all the way $$$ highly recommend",
  },
  {
    service: "Robux",
    text: "vouch been buying robux here for years never had a single issue, VeeX trusted forever",
  },
  {
    service: "General",
    text: "vouch idk how the prices are this cheap but everything legit no cap, real deal",
  },
  {
    service: "R6 Credits",
    text: "22k r6 credits for cheap af, fast delivery and super nice support, was suspicious at first but all good +rep VeeX",
  },
  {
    service: "Valorant Points",
    text: "prices are insane ty for the vp 🔥 VeeX best seller",
  },
  {
    service: "Robux",
    text: "+vouch VeeX just got 50k robux in under 5 mins, cheapest and fastest ever 🔥 trusted 100%",
  },
  {
    service: "V-Bucks",
    text: "bought 40k vbucks gift cards, redeemed instantly no issues, ty veex bro legit af",
  },
  {
    service: "Fortnite Account",
    text: "stacked og fn account with renegade raider, full access delivered quick, VeeX is the goat fr",
  },
  {
    service: "Valorant Points",
    text: "49k vp for stupid cheap, code worked perfect, big vouch for VeeX safe and fast",
  },
  {
    service: "R6 Credits",
    text: "+rep veex 100k r6 credits smooth transaction, most trusted seller out here",
  },
  {
    service: "Headless",
    text: "headless acc traded clean and fast, no scams, VeeX highly recommended",
  },
  {
    service: "Korblox",
    text: "finally got korblox on my main thanks to VeeX, legit trade went first no problem",
  },
  {
    service: "COD Bot Lobby",
    text: "mw3 bot lobby worked flawless, leveled up crazy fast, ty VeeX trusted service",
  },
  {
    service: "General",
    text: "been buying from VeeX for months, always delivers, cheapest prices and super chill +vouch",
  },
  {
    service: "Valorant Account",
    text: "immortal ranked val acc with reaver vandal, full email change, VeeX real deal no cap",
  },
  {
    service: "Robux",
    text: "80k robux group funds method, instant and safe, vouch VeeX best plug",
  },
  {
    service: "Fortnite Bot Lobby",
    text: "fn bot lobby for arena points, got to unreal easy, VeeX service 10/10",
  },
  {
    service: "General",
    text: "+vouch veex paid crypto got everything in minutes, most reliable seller",
  },
  {
    service: "R6 Account",
    text: "champ r6 acc with black ice, full access, ty VeeX fast delivery",
  },
  {
    service: "Valorant Points",
    text: "bought 100k vp bundle, all codes valid, VeeX trusted forever 🫶",
  },
  {
    service: "General",
    text: "VeeX is the only legit seller left in this market, fast cheap safe, big vouch ++ will keep buying",
  },
  // ... (الباقي من الـ 500+ vouch موجود كامل في النسخة اللي عندك، مش محتاج أكرره هنا عشان الطول)
]

export const USER_NAMES = [
  "Liam Nelson",
  "Olivia Henderson",
  "Jackson Williams",
  "Emma Rodriguez",
  "Noah Davis",
  "Sophia Martinez",
  "William Brown",
  "Isabella Garcia",
  "James Miller",
  "Ava Wilson",
  "Benjamin Moore",
  "Charlotte Taylor",
  "Elijah Anderson",
  "Amelia Thomas",
  "Lucas Jackson",
  "Mia White",
  "Henry Harris",
  "Harper Martin",
  "Alexander Clark",
  "Evelyn Lewis",
  "Daniel Walker",
  "Abigail Hall",
  "Matthew Allen",
  "Emily Young",
  "Jack Baker",
  "Chloe Scott",
  "David Adams",
  "Grace Green",
  "Ryan King",
  "Zoe Carter",
  "Nathan Wright",
  "Lily Perez",
  "Samuel Torres",
  "Avery Rivera",
  "Owen Gomez",
  "Victoria Flores",
  "Gabriel Cooper",
  "Addison Bell",
  "Andrew Murphy",
  "Scarlett Rogers",
  "Jaxon Bailey",
  "Penelope Cox",
  "Dylan Isaac",
  "Tyler Sanders",
  "xX_SniperElite_Xx",
  "MikeTango47",
  "Gaming_Dad_35",
  "Viper_Queen",
  "GhostlyTrader",
  "ApexLegend77",
  "ShadowHunter",
  "ToxicGamer21",
  "CodeBreaker_1",
  "TheMasterPro",
  "KingCrimson_99",
  "DarkSlayer",
  "StealthModeON",
  "AlphaPvP",
  "VoidRunner",
  "LegendaryMike",
  "R6S_Prodigy",
  "RobloxGeek88",
  "FN_Boss",
  "CodSkinsGuy",
  "ValorantKing",
  "Mikey_V",
  "TangoFoxtrot",
  "EchoDelta_23",
  "GamerGirl_95",
  "CyberPhoenix",
  "NeonSpecter",
  "ZeroLatency",
  "RaidBoss_EU",
  "SoloQ_Carry",
  "FastCashFlow",
  "CryptoLord",
  "DigitalNomad",
  "PixelWarrior",
  // الأسماء الجديدة الحقيقية المضافة
  "Ethan Thompson",
  "Mason Johnson",
  "Logan Smith",
  "Jacob Evans",
  "Michael Roberts",
  "Daniel Turner",
  "Christopher Phillips",
  "Joshua Campbell",
  "Andrew Parker",
  "Matthew Edwards",
  "David Collins",
  "Joseph Stewart",
  "Thomas Morris",
  "Charles Rogers",
  "Jennifer Mitchell",
  "Elizabeth Davies",
  "Sarah Hughes",
  "Jessica Price",
  "Ashley Ward",
  "Amanda Wood",
  "Melissa Turner",
  "Laura Walker",
  "Rebecca Hall",
  "Michelle Allen",
  "Kimberly Young",
  "Deborah Hernandez",
  "Cynthia King",
  "Patricia Wright",
  "Linda Lopez",
  "Barbara Hill",
  "Susan Scott",
  "Margaret Green",
  "Dorothy Adams",
  "Lisa Baker",
  "Nancy Gonzalez",
  "Karen Nelson",
  "Betty Carter",
  "Helen Mitchell",
  "Sandra Perez",
  "Donna Roberts",
  "Carol Turner",
  "Ruth Phillips",
  "Sharon Campbell",
  "Emily Parker",
  "Sophie Clarke",
  "Isabelle Bennett",
  "Grace Cooper",
  "Freya Richardson",
  "Poppy Wood",
  "Evie Ward",
  "Elsie Thomson",
  "Mia Harrison",
  "Lily Bell",
  "Oliver Shaw",
  "Harry Gray",
  "Jack Murphy",
  "Charlie Kelly",
  "Thomas Rivera",
  "George Russell",
  "Oscar Griffin",
  "Henry Murray",
  "Alfie Hunt",
  "Archie Fletcher",
  "Theo Ellis",
  "Finley Rose",
  "Leo Brooks",
  "Max Porter",
  "Luca Hamilton",
  "Jude Webb",
  "Harrison Knight",
  "Blake Foster",
  "Cameron Grant",
  "Riley Armstrong",
  "Dylan Fraser",
  "Sebastian Mackay",
  "Adam Johnston",
  "Nathan Cameron",
  "Callum Anderson",
  "Brandon Stewart",
  "Connor MacDonald",
  "Lewis Gordon",
  "Kai Henderson",
  "Aaron Murray",
  "Owen Robertson",
  "Joshua Campbell",
  "Ryan Sinclair",
  "David McKenzie",
  "Scott Ferguson",
  "Fraser Ross",
  "Blake Morrison",
  "Jayden Paterson",
  "Caleb Watson",
  "Tyler Graham",
  "Reuben Hunter",
  "Alex Miller",
  "Corey Reid",
  "Ellis Thomson",
  "Harris Wilson",
  "Jamie Duncan",
  "Kyle MacLeod",
  "Leon Black",
  "Murray Simpson",
  "Rory Kennedy",
  "Taylor Marshall",
  "Zac Jenkins",
  "Arlo Palmer",
  "Beau Sullivan",
  "Cody Fletcher",
  "Dexter Hayes",
  "Eli Lawson",
  "Finn Moran",
  "Gage Nichols",
  "Hank Osborne",
  "Ivan Pierce",
  "Jett Quinn",
  "Kane Reeves",
  "Landon Stone",
  "Milo Tucker",
  "Nico Vargas",
  "Otto Walsh",
  "Peyton Yates",
  "Quinn Zimmerman",
  "Ronan Becker",
  "Silas Donovan",
  "Tate Everett",
  "Uriel Frazier",
  "Vance Garrison",
  "Wyatt Holloway",
  "Xander Ingram",
  "Yosef Jensen",
  "Zane Keller",
  "Brody Larson",
  "Colton Manning",
  "Declan Nolan",
  "Easton Owens",
  "Flynn Powers",
  "Grady Ramsey",
  "Holden Sawyer",
  "Iker Tate",
  "Jasper Vaughn",
  "Knox Walsh",
  "Luka Yates",
  "Maddox Becker",
  "Nolan Cross",
  "Orion Doyle",
  "Paxton Ellis",
  "Quincy Ford",
  "Remy Gibson",
  "Sawyer Hale",
  "Tatum Irvine",
  "Ulysses Kane",
  "Vaughn Levy",
  "Wilder Moss",
  "Xavier Nash",
  "Yuri Ortiz",
  "Zephyr Payne",
]

export function generateUniqueUsername(index: number, availableNames: string[]): string {
  if (index < availableNames.length) {
    const randomIndex = Math.floor(Math.random() * availableNames.length)
    const selectedName = availableNames[randomIndex]
    availableNames.splice(randomIndex, 1)
    return selectedName.replace(/_/g, " ")
  } else {
    const fallbackName = USER_NAMES[index % USER_NAMES.length]
    return fallbackName.replace(/_/g, " ")
  }
}

export function generateTimeAgo(vouchIndex: number): string {
  if (vouchIndex < 50) {
    const minutes = Math.floor(Math.random() * 59) + 1;
    const hours = Math.floor(Math.random() * 23);
    if (hours === 0) return `${minutes} minute${minutes > 1 ? "s" : ""} ago`;
    return `${hours} hour${hours > 1 ? "s" : ""} ago`;
  } else if (vouchIndex < 150) {
    const days = Math.floor(Math.random() * 6) + 1;
    return `${days} day${days > 1 ? "s" : ""} ago`;
  } else {
    const start = new Date(2025, 0, 1); // Jan 2025
    const end = new Date(2025, 11, 19); // Dec 19 2025
    const randomDate = new Date(start.getTime() + Math.random() * (end.getTime() - start.getTime()));
    return randomDate.toLocaleDateString("en-US", { year: "numeric", month: "short", day: "numeric" });
  }
}
